@TOKEN = Bearer a87sd6f8asdfb7b6s8d7f6a8s6dbf8sa6df9a6sd98bfa6sdf986asd9fa69s7d5f7z5xc76v5z7cxvb7
@PORT = 8888

### GET-LOCALHOST 
GET http://localhost:{{PORT}}/aaa/bbb/ccc/GetUser?e=5#wow


### POST-LOCALHOST
POST http://localhost:{{PORT}}/api/v1/GetUser HTTP/1.1
Content-Type: application/json

{
    "key1": "vscode-restclient",
    "key2": "Huachao"
}


### GraphQL
POST http://localhost:{{PORT}}/graphql HTTP/1.1
Content-Type: application/json
X-REQUEST-TYPE: GraphQL
Authorization: {{TOKEN}}

query MyTestQuery($id: String!, $customer: String, $product: String!) {
  myTestQuery( id: $id customer: $customer product: $product ) {
    data {
      product
      serialno
    }
  }
}

{
    "id": "1234",
    "customer": "9876",
    "product": "ABC"
}
